-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.appointments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    pet_id uuid NOT NULL,
    service_id uuid,
    appointment_date timestamp without time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.breed_recommendations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    breed_id uuid NOT NULL,
    product_id uuid,
    service_id uuid,
    recommendation_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    recommendation_reason text COLLATE pg_catalog."default",
    priority integer DEFAULT 0,
    CONSTRAINT breed_recommendations_pkey PRIMARY KEY (id),
    CONSTRAINT breed_recommendations_breed_id_product_id_key UNIQUE (breed_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.breeds
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    display_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    species character varying(10) COLLATE pg_catalog."default" NOT NULL,
    fur_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    size_category character varying(20) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT breeds_pkey PRIMARY KEY (id),
    CONSTRAINT breeds_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    subtotal numeric(12, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    order_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    delivery_method character varying(20) COLLATE pg_catalog."default" DEFAULT 'pickup'::character varying,
    shipping_address text COLLATE pg_catalog."default",
    shipping_fee numeric(12, 2) DEFAULT 0,
    receiver_name character varying(100) COLLATE pg_catalog."default",
    receiver_phone character varying(20) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT orders_order_number_key UNIQUE (order_number)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    appointment_id uuid,
    order_id uuid,
    payment_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    amount numeric(12, 2) NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    transaction_id character varying(100) COLLATE pg_catalog."default",
    transaction_date timestamp without time zone DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pets
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    owner_id uuid NOT NULL,
    breed_id uuid,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    species character varying(10) COLLATE pg_catalog."default" NOT NULL,
    breed character varying(100) COLLATE pg_catalog."default",
    fur_length character varying(20) COLLATE pg_catalog."default",
    weight numeric(5, 2),
    gender character varying(10) COLLATE pg_catalog."default",
    age integer,
    image_url text COLLATE pg_catalog."default",
    medical_history text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT pets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    icon character varying(50) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    display_order integer DEFAULT 0,
    CONSTRAINT product_categories_pkey PRIMARY KEY (id),
    CONSTRAINT product_categories_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.product_reviews
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    product_id uuid NOT NULL,
    user_id uuid NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
    CONSTRAINT product_reviews_product_id_user_id_key UNIQUE (product_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    category_id uuid,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(12, 2) NOT NULL,
    sale_price numeric(12, 2),
    stock_quantity integer DEFAULT 0,
    sku character varying(50) COLLATE pg_catalog."default",
    image_url text COLLATE pg_catalog."default",
    images jsonb DEFAULT '[]'::jsonb,
    target_species character varying(20) COLLATE pg_catalog."default",
    target_fur_type character varying(20) COLLATE pg_catalog."default",
    target_size character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    rating_avg numeric(3, 2) DEFAULT 0,
    rating_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_sku_key UNIQUE (sku),
    CONSTRAINT products_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.scan_results
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid,
    pet_id uuid,
    breed_id uuid,
    confidence numeric(5, 4) NOT NULL,
    image_url text COLLATE pg_catalog."default" NOT NULL,
    top_3_predictions jsonb,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT scan_results_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.services
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    price numeric(12, 2) NOT NULL,
    duration_minutes integer,
    target_species character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    image_url text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT services_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(20) COLLATE pg_catalog."default",
    avatar_url text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'customer'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.vaccinations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    pet_id uuid NOT NULL,
    vaccine_type_id uuid NOT NULL,
    administered_by uuid,
    dose_number integer DEFAULT 1,
    vaccination_date date NOT NULL,
    next_due_date date,
    batch_number character varying(50) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'completed'::character varying,
    created_at timestamp without time zone DEFAULT now(),
    CONSTRAINT vaccinations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vaccine_types
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    target_species character varying(10) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    recommended_age_months integer,
    interval_days integer,
    doses_required integer DEFAULT 1,
    CONSTRAINT vaccine_types_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.pets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.appointments
    ADD CONSTRAINT appointments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_appointments_user
    ON public.appointments(user_id);


ALTER TABLE IF EXISTS public.breed_recommendations
    ADD CONSTRAINT breed_recommendations_breed_id_fkey FOREIGN KEY (breed_id)
    REFERENCES public.breeds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.breed_recommendations
    ADD CONSTRAINT breed_recommendations_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.breed_recommendations
    ADD CONSTRAINT breed_recommendations_service_id_fkey FOREIGN KEY (service_id)
    REFERENCES public.services (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_user
    ON public.orders(user_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_appointment_id_fkey FOREIGN KEY (appointment_id)
    REFERENCES public.appointments (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pets
    ADD CONSTRAINT pets_breed_id_fkey FOREIGN KEY (breed_id)
    REFERENCES public.breeds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pets
    ADD CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_pets_owner
    ON public.pets(owner_id);


ALTER TABLE IF EXISTS public.product_reviews
    ADD CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.product_reviews
    ADD CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.product_categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_products_category
    ON public.products(category_id);


ALTER TABLE IF EXISTS public.scan_results
    ADD CONSTRAINT scan_results_breed_id_fkey FOREIGN KEY (breed_id)
    REFERENCES public.breeds (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.scan_results
    ADD CONSTRAINT scan_results_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.pets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.scan_results
    ADD CONSTRAINT scan_results_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_scan_user
    ON public.scan_results(user_id);


ALTER TABLE IF EXISTS public.vaccinations
    ADD CONSTRAINT vaccinations_administered_by_fkey FOREIGN KEY (administered_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vaccinations
    ADD CONSTRAINT vaccinations_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.pets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_vaccinations_pet
    ON public.vaccinations(pet_id);


ALTER TABLE IF EXISTS public.vaccinations
    ADD CONSTRAINT vaccinations_vaccine_type_id_fkey FOREIGN KEY (vaccine_type_id)
    REFERENCES public.vaccine_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;