# -*- coding: utf-8 -*-
"""dogcatcls.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CpXxh5T02oFdDUCsoBZH6V6aCfqkZGtF
"""

import zipfile
import os

zip_file_path = '/content/drive/MyDrive/datasetoxfordclass.zip'
extraction_path = '/content/'

# Create the extraction directory if it doesn't exist
os.makedirs(extraction_path, exist_ok=True)

# Extract the zip file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f"File '{zip_file_path}' has been extracted to '{extraction_path}'.")

# List the contents of the extracted directory to verify
print("Contents of the extracted directory:")
for item in os.listdir(extraction_path):
    print(item)

import os

annotations_path = '/content/annotations'

print(f"Listing all files recursively in '{annotations_path}':")

if os.path.exists(annotations_path) and os.path.isdir(annotations_path):
    for root, dirs, files in os.walk(annotations_path):
        for file in files:
            print(os.path.join(root, file))
else:
    print(f"Error: Directory '{annotations_path}' not found or is not a directory.")

!pip install tensorflow tensorflowjs

import tensorflow as tf
tf.config.list_physical_devices("GPU")

import os
import numpy as np

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# SỬA PATH Ở ĐÂY
DATA_DIR = "/content/images/images"  # Updated path
LABEL_FILE = "/content/annotations/annotations/list.txt"

image_paths = []
labels = []

with open(LABEL_FILE, "r") as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.strip().split()
        filename = parts[0] + ".jpg"
        label = int(parts[1]) - 1
        image_paths.append(os.path.join(DATA_DIR, filename))
        labels.append(label)

num_classes = len(set(labels))
print("Classes:", num_classes)

image_paths = np.array(image_paths)
labels = np.array(labels)

idx = np.random.permutation(len(image_paths))
image_paths = image_paths[idx]
labels = labels[idx]

split = int(0.8 * len(image_paths))
train_paths, val_paths = image_paths[:split], image_paths[split:]
train_labels, val_labels = labels[:split], labels[split:]

def load_image(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0
    return img, label

train_ds = tf.data.Dataset.from_tensor_slices((train_paths, train_labels))
train_ds = train_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)\
                   .shuffle(1000)\
                   .batch(BATCH_SIZE)\
                   .prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices((val_paths, val_labels))
val_ds = val_ds.map(load_image, num_parallel_calls=tf.data.AUTOTUNE)\
               .batch(BATCH_SIZE)\
               .prefetch(tf.data.AUTOTUNE)

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights="imagenet"
)

base_model.trainable = False  # freeze backbone

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(num_classes, activation="softmax")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

EPOCHS = 10

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)

MODEL_DIR = "/content/oxford_pet_model"

model.save(MODEL_DIR)
print("Saved model to:", MODEL_DIR)

import tensorflow as tf

model = tf.keras.models.load_model("/content/oxford_pet_model.keras")
model.export("/content/oxford_pet_savedmodel")

!ls /content/oxford_pet_savedmodel

!tensorflowjs_converter \
  --input_format=tf_saved_model \
  --output_format=tfjs_graph_model \
  /content/oxford_pet_savedmodel \
  /content/tfjs_model

!zip -r tfjs_model.zip /content/tfjs_model

from google.colab import files
files.download("tfjs_model.zip")